trigger:
- main  # or 'master' depending on your branch

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: Maven@3
  inputs:
    mavenPomFile: 'pom.xml'
    goals: 'package'
    publishJUnitResults: true
    testResultsFiles: '/surefire-reports/TEST-*.xml'
